import localFont from "next/font/local";
import "./globals.css";
import AppContextProvider from "./components/GlobalContextApp";
import { Toaster } from "@/components/ui/toaster";

// Configuración de las fuentes locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900", // Especifica el rango de peso como cadena
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900", // Especifica el rango de peso como cadena
});

// Metadata para el documento
export const metadata = {
  title: "TecNM - CIMS",
  description: "Generated by create next app",
};

// Componente de Layout raíz
export default function RootLayout({ children }) {
  if (!children) {
    throw new Error(
      "El componente RootLayout necesita 'children' para renderizar correctamente."
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-1 text-gray-600`}
      >
        <AppContextProvider>
          {children}
          <Toaster />
        </AppContextProvider>
      </body>
    </html>
  );
}
